---
- hosts: localhost
  vars:
  - ansible_ec2_instance_id: i-03f7d9f815835e98a
  - ansible_ec2_placement_region: ap-south-1

  tasks:
  - name: Gather EC2 instance metadata
    action: ec2_metadata_facts
  - name: Gather EC2 instance metadata
    #action: ec2_instance_facts
    ec2_remote_facts:
     region: "{{ ansible_ec2_placement_region }}"
    register: ec2_facts

  - name: Obtain EC2 tags for this instance
    local_action:
      module: ec2_tag
      region: "{{ ansible_ec2_placement_region }}"
      resource: "{{ item }}"
      state: list
    register: ec2_tags
    with_items: "{{ ec2_facts.instances|selectattr('state', 'equalto', 'running')|map(attribute='id')|list }}"

  - debug:
     msg: "{{ ec2_tags.results |map(attribute='item')|list}}, {{ ec2_tags.results |map(attribute='tags')|list}}"

  - name: "Creating Instance ID's file"
    shell: echo "Instance ID : {{ item }}" >./instanceid
    with_nested: 
     - "{{ ec2_tags.results |map(attribute='item')|list}}"
    
  - name: "Creating Tag Result file"
    shell: echo "Tag Value : {{ item }}" >./tags
    with_nested: 
     - "{{ ec2_tags.results |map(attribute='tags')|list}}"
    when: ("{{ item }}" == "{}")

