---
- hosts: localhost
  vars:
  - ansible_ec2_instance_id: i-03f7d9f815835e98a
  - ansible_ec2_placement_region: ap-south-1

  tasks:
  - name: Gather EC2 instance metadata
    action: ec2_metadata_facts
  - name: Gather EC2 instance metadata
    #action: ec2_instance_facts
    ec2_remote_facts:
     region: "{{ ansible_ec2_placement_region }}"
    register: ec2_facts

  - name: Obtain EC2 tags for this instance
    local_action:
      module: ec2_tag
      region: "{{ ansible_ec2_placement_region }}"
      resource: "{{ ansible_ec2_instance_id }}"
      state: list
    register: ec2_tags

  - debug:
     msg: "{{ ec2_tags.tags }} {{ ec2_facts.instances|selectattr('state', 'equalto', 'running')|map(attribute='id')|list }}"
     #msg: "Anuj"
     
  - name: add several users
    debug:
     msg: "{{item}}"
    with_nested: 
     - "{{ ec2_facts.instances|selectattr('state', 'equalto', 'running')|map(attribute='id')|list }}"

  - name: "Creating Result file"
    shell: echo "Instance ID having Null Tag is {{ ansible_ec2_instance_id }}" > a.txt
    when: (ec2_tags.tags == {})
