---
- hosts: servers
  vars:
  - downloadURL: https://tomcat.apache.org/tomcat-6.0-doc/appdev/sample/sample.war
  - zipName: BIGFIX-CLIENT-CENTOS-OEL-RHEL
  - RemotePath: /tmp

  tasks:
  - name: install the latest version of Apache
    yum:
      name: unzip
      state: latest
      
  - name: Download BIGFIX Client to server
    command: wget {{downloadURL}} -O {{ RemotePath }}/{{ zipName }}.zip
   
  - name: Unarchive a file that is already on the remote machine
    unarchive:
      src: "{{ RemotePath }}/{{ zipName }}.zip"
      dest: /tmp
      remote_src: yes
      
  - name: Creates BES Client directory
    file:
      path: /etc/opt/BESClient
      state: directory
      owner: root
      group: root
      mode: 0775
      recurse: yes
      
  - name: Install Big Fix RPM locally
    yum:
      name: "/tmp/{{ RemotePath }}/{{ zipName }}/*.rpm"
      state: present
      
  - copy:
      src: "/tmp/{{ RemotePath }}/{{ zipName }}/iem-cps_actionsite.afxm"
      dest: /etc/opt/BESClient/actionsite.afxm
      owner: root
      group: root
      mode: 0644
      
  - service:
    name: besclient
    enabled: yes
    
  - service:
    name: besclient
    state: restarted
