---
- hosts: localhost
  vars:
  - ansible_ec2_instance_id: i-03f7d9f815835e98a
  - ansible_ec2_placement_region: ap-south-1

  tasks:
  - name: Gather EC2 instance metadata
    action: ec2_metadata_facts
  - name: Gather EC2 instance metadata
    #action: ec2_instance_facts
    ec2_remote_facts:
     region: "{{ ansible_ec2_placement_region }}"
    register: ec2_facts

  - name: Obtain EC2 tags for this instance
    local_action:
      module: ec2_tag
      region: "{{ ansible_ec2_placement_region }}"
      resource: "{{ item }}"
      state: list
    register: ec2_tags
    with_items: "{{ ec2_facts.instances|selectattr('state', 'equalto', 'running')|map(attribute='id')|list }}"

  - block:
    - name: Remove Temporary files
      file:
          path: "{{ item }}"
          state: absent
      with_items:
        - instanceid
        - tags
    ignore_errors: yes 

  - name: "Creating Instance ID's file"
    shell: echo "Instance ID  {{ item }}" >>./instanceid
    with_items: 
     - "{{ ec2_tags.results |map(attribute='item')|list}}"
    
  - name: "Creating Tag Result file"
    shell: echo "Tag Value  {{ item }}" >>./tags
    with_items: 
     - "{{ ec2_tags.results |map(attribute='tags')|list}}"
    #when: ( "{{ item }}" == "{}")
   
  - name: "Join Result Files"
    shell: paste ./instanceid ./tags | grep '{}'> final
    register: cmdln
    failed_when: "cmdln.rc == 2"
    check_mode: no
 
  - name: Sending Email 
    mail:
     host: 127.0.0.1
     port: 25
     subject: Ansible-report
     body: Hello, this is an e-mail. I hope you like it ;-)
     from: playbook@Ansible.net (Ansible Playbook)
     to: Anuj Sharma <anuj_sharma401@yahoo.com>, Vinay Raj <vinayraj404@gmail.com>
     cc: Server Root <root@localhost>
     attach: ./playbook.yaml ../final
     headers: 'Reply-To=vinayraj404@gmail.com|X-Special="Something or other"'
     charset: utf8
    delegate_to: localhost
